# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class App:
        name: str
        stage: str
    class ModelService:
        service: str
        type: str
        url: str
    class ModelVpc:
        type: str
    class Predictions:
        name: str
        type: str

