name: CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  typecheck:
    name: Typescript Type Check
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - run: npm ci 
      - run: npx tsc --noEmit -p packages/api/tsconfig.json

  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7 
      - uses: astral-sh/setup-uv@v7
        with:
          version: latest
      - run: uv tool install ruff
      - run: ruff check container/ ml/ main.py


